### PR TITLE
Support for custom tests

### PR DESCRIPTION
**Pull request by woodt**
Adds two new dktl commands, dktl test:behat-custom and dktl test:phpunit-custom.

Connects #20

### CODE REVIEW

**Comment by dafeder** [comment]
Since this PR was submitted the test commands for D7 have changed location -- should be fairly easy to move them there and resolve the conflict @woodt.

Also, can you either write some QA steps for me or plan some time to review the functionality together.

**Comment by woodt** [comment]
So I moved the commands into Drupal/V7 and also refactored the "common" test code into a trait (anticipating the possible future of some commands living in the 'dkan' namespace, and some in the 'test' namespace, as in D8.)  Also cleaned up some logic in dktl.

QA steps:

- [ ] `dktl test:phpunit` should run existing core tests
- [ ] `dktl test:behat` should run existing behat tests
- [ ] Create src\test\phpunit and populate with a boot.php, phpunit.xml, and a sample test.  `dktl test:phpunit-custom` should run the sample custom test.
- [ ] Create src\test\behat.yml, src\test\behat.docker.yml, and src\test\features containing a sample behat test.  `dktl test:behat-custom` should run the sample behat test.

**Comment by dafeder** [comment]
Hi @woodt  - would you mind adding sample behat and phpunit tests to the ticket so it's a little easier to do the QA here?

Also, the init command creates a "src/tests" directory, when according to the docs here it should be just "test" - let's fix that as well as part of this PR. That's in _src/Drupal/V7/InitiCommands.php_

**Comment by woodt** [comment]
[https://app.zenhub.com/files/132668094/cd684bdf-da56-4d33-8004-1d719fdb5d6a/download](https://app.zenhub.com/files/132668094/cd684bdf-da56-4d33-8004-1d719fdb5d6a/download)

**Comment by woodt** [comment]
@dafeder -- updated with the changes we discussed yesterday (also rebased against master.)

**Pull request merged**
