### PR TITLE
Use data-catalog-react as the default frontend repo

### PR DESCRIPTION
**Pull request by janette**
Using a Gatsby-based frontend is not working out as planned. Switching to a Create REACT App-bassed frontend will provide less confusion and rebuilding for dynamic content.

- Changed the symlinked directory in Docroot to 'frontend'
- Add option to use alternate frontend applications by passing the url of the repo

## QA steps

- run `dktl make --frontend`, confirm you get the data-catalog-react repo symlinked to docroot/frontend
- delete src/frontend
- run `dktl make --frontend --fe-repo=https://github.com/GetDKAN/data-catalog-frontend.git`, confirm you get the gatsby version

### CODE REVIEW

**Comment by janette** [comment]
@dgading I'll work on the codeclimate issues but it works so you can test it with the new frontend.

**Comment by dafeder** [comment]
`make --frontend` refuses to download if src/frontend already exists... this seems wrong.

**Comment by janette** [comment]
@dafeder did you get a message that it already exits? that is to prevent accidental overrides of existing code

**Comment by dafeder** [comment]
I understand but still seems unexpected... at minimum, i think the error message should give you some other options. Not a huge priority I guess.

**Comment by janette** [comment]
closing in favor of  #253

**Pull request closed without merging**
